// <auto-generated />
using FFXICustomDats.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FFXICustomDats.Migrations
{
    [DbContext(typeof(XiDatContext))]
    [Migration("20251120021758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.Item", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemid");

                    b.Property<string>("DatFile")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("dat_file");

                    b.Property<uint>("Flags")
                        .HasColumnType("int(8) unsigned")
                        .HasColumnName("flags");

                    b.Property<byte[]>("IconBytes")
                        .HasColumnType("blob")
                        .HasColumnName("icon_bytes");

                    b.Property<byte>("ItemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1) unsigned")
                        .HasColumnName("type")
                        .HasDefaultValueSql("@`GENERAL_TYPE`");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int(11)")
                        .HasColumnName("resource_id");

                    b.Property<byte>("StackSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(2) unsigned")
                        .HasColumnName("stackSize")
                        .HasDefaultValueSql("'1'");

                    b.Property<ushort>("ValidTargets")
                        .HasColumnType("smallint(3) unsigned")
                        .HasColumnName("validTargets");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemEquipment", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemId");

                    b.Property<byte>("CastingTime")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("castingTime");

                    b.Property<byte>("ILevel")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("ilevel");

                    b.Property<uint>("Jobs")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("jobs");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("level");

                    b.Property<byte>("MaxCharges")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("maxCharges");

                    b.Property<ushort>("Races")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("races");

                    b.Property<uint>("ReuseDelay")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("reuseDelay");

                    b.Property<byte>("ShieldSize")
                        .HasColumnType("tinyint(1) unsigned")
                        .HasColumnName("shieldSize");

                    b.Property<ushort>("Slot")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("slot");

                    b.Property<byte>("SuperiorLevel")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("superior_level");

                    b.Property<int>("Unknown1")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown1");

                    b.Property<int>("Unknown2")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown2");

                    b.Property<int>("Unknown3")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown3");

                    b.Property<byte>("UseDelay")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("useDelay");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item_equipment", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemFurnishing", b =>
                {
                    b.Property<ushort>("Itemid")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemid");

                    b.Property<byte>("Element")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("element");

                    b.Property<byte>("Storage")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("storage");

                    b.Property<int>("Unknown3")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown3");

                    b.HasKey("Itemid")
                        .HasName("PRIMARY");

                    b.ToTable("item_furnishing", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemPuppet", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemid");

                    b.Property<int>("Dark")
                        .HasColumnType("int(11)")
                        .HasColumnName("dark");

                    b.Property<int>("Earth")
                        .HasColumnType("int(11)")
                        .HasColumnName("earth");

                    b.Property<int>("Fire")
                        .HasColumnType("int(11)")
                        .HasColumnName("fire");

                    b.Property<int>("Ice")
                        .HasColumnType("int(11)")
                        .HasColumnName("ice");

                    b.Property<int>("Light")
                        .HasColumnType("int(11)")
                        .HasColumnName("light");

                    b.Property<int>("Lightning")
                        .HasColumnType("int(11)")
                        .HasColumnName("lightning");

                    b.Property<byte>("Slot")
                        .HasColumnType("tinyint(2) unsigned")
                        .HasColumnName("slot");

                    b.Property<int>("Unknown1")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown1");

                    b.Property<int>("Water")
                        .HasColumnType("int(11)")
                        .HasColumnName("water");

                    b.Property<int>("Wind")
                        .HasColumnType("int(11)")
                        .HasColumnName("wind");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item_puppet", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemString", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemid");

                    b.Property<ushort>("ArticleType")
                        .HasColumnType("smallint(3) unsigned")
                        .HasColumnName("articleType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("name");

                    b.Property<string>("PluralName")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("plural_name");

                    b.Property<string>("SingularName")
                        .IsRequired()
                        .HasColumnType("tinytext")
                        .HasColumnName("singular_name");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item_string", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemUsable", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemId");

                    b.Property<byte>("ActivationTime")
                        .HasColumnType("tinyint(3) unsigned")
                        .HasColumnName("activationTime");

                    b.Property<int>("Unknown1")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown1");

                    b.Property<int>("Unknown2")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown2");

                    b.Property<int>("Unknown3")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown3");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item_usable", (string)null);
                });

            modelBuilder.Entity("FFXICustomDats.Data.XiDatEntities.ItemWeapon", b =>
                {
                    b.Property<ushort>("ItemId")
                        .HasColumnType("smallint(5) unsigned")
                        .HasColumnName("itemId");

                    b.Property<uint>("Damage")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("dmg");

                    b.Property<int>("Delay")
                        .HasColumnType("int(10)")
                        .HasColumnName("delay");

                    b.Property<int>("Dps")
                        .HasColumnType("int(10)")
                        .HasColumnName("dps");

                    b.Property<int>("JugSize")
                        .HasColumnType("int(10)")
                        .HasColumnName("jugSize");

                    b.Property<uint>("SkillType")
                        .HasColumnType("int(10) unsigned")
                        .HasColumnName("skillType");

                    b.Property<int>("Unknown1")
                        .HasColumnType("int(11)")
                        .HasColumnName("unknown1");

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.ToTable("item_weapon", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
